# Generated by Django 4.2 on 2023-04-12 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='path_to_img',
            field=models.CharField(default='none', max_length=100),
        ),
    ]
