# Generated by Django 4.2 on 2023-04-17 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_table', models.CharField(max_length=10)),
                ('state', models.BooleanField(default=True)),
                ('count_person', models.IntegerField()),
            ],
        ),
    ]
