# Generated by Django 4.2 on 2023-04-12 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MenuPosition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=25, verbose_name='Название')),
                ('date', models.DateTimeField(verbose_name='Дата создания')),
                ('anons', models.CharField(max_length=35, verbose_name='Короткое описание')),
                ('path_to_img', models.CharField(max_length=100, verbose_name='Путь к картинке')),
                ('price', models.IntegerField(verbose_name='Цена')),
                ('tag', models.CharField(default='none', max_length=50, verbose_name='Тип еды')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Позиции товаров',
            },
        ),
    ]
